### ISSUE TITLE
Group.characteristic - Alignement des ValueSet

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-essais-cliniques#102]
## Description du problème
Pour faire suite à l'issue #93 

![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/122790741/5d9d69dc-2c55-47b7-b830-843b9dddfa94)

Plusieurs points : 

1. La nomenclature associée à l'attribut code ne devrait -elle pas être positionnée au niveau de la value pour le cas ou le type de caractéristique est "study population"
2. Devons nous créer une nomenclature pour le type de caractéristique ( = attribut code), en reprenant les valeurs de l'exemple ? 
Genders / Research Study Group Category / Study Population + ajouter age ? 
3. Dans la sortie du Swagger, on peut remarquer qu'il y a deux instances de characteristic pour Study Inclusion Criteria et Study Exclusion Criteria. Quelle valeur est prévue pour ces instances ? Il me semble que ces points sont déjà traités via l'attribut "exclude"
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/122790741/a24e7a56-d0f4-404d-a028-ad6339291cdb)

## Fichier•s concerné•s
[eclaire-group](https://interop.esante.gouv.fr/ig/fhir/eclaire/StructureDefinition-eclaire-group.html)

**Comment by paulineheurtebise** [comment]
@sbedeau : pour en échanger

**Comment by paulineheurtebise** [comment]
Issues créées dans le GIT DNUM : 

- [ ] [Group.characteristic.code - Contenu du valueSet #143 ](https://github.com/DNUM-SocialGouv/eclaire/issues/143)
- [ ] [Group.characteristic - bloc critere inclusion exclusion #142 ](https://github.com/DNUM-SocialGouv/eclaire/issues/142)
- [ ]  [Information portée par le champs "Text" dans les attributs de type CodeableConcept #144 ](https://github.com/DNUM-SocialGouv/eclaire/issues/144)

**Comment by paulineheurtebise** [comment]
Exemple fourni dans l'issue [144](https://github.com/DNUM-SocialGouv/eclaire/issues/144)

**Comment by paulineheurtebise** [comment]
Réunion du 08/01 : contenu du CodeSystem pour le type de characteristic
- Gender
- Study Population
- Research Study Group Category
- Age
- Other
